<a href="https://colab.research.google.com/github/MERITOKAMIL/ML_PRO/blob/master/Diagonalisation_matricielle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
import scipy.stats as stats
import statsmodels.api as sm
from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm
from statsmodels.stats.multicomp import pairwise_tukeyhsd
import sympy as sp


In [19]:
B=np.array([[1,-1,4],[3, 2,-1],[2, 1, -1]])
B

array([[ 1, -1,  4],
       [ 3,  2, -1],
       [ 2,  1, -1]])

In [20]:
import numpy as np

def est_diagonalisable(A):
    # Calcul des valeurs propres et des vecteurs propres
    valeurs_propres, vecteurs_propres = np.linalg.eig(A)

    # Nombre de valeurs propres distinctes
    valeurs_propres_uniques = np.unique(valeurs_propres)

    # Vérifier si la matrice possède suffisamment de vecteurs propres linéairement indépendants
    rang_vecteurs = np.linalg.matrix_rank(vecteurs_propres)

    return rang_vecteurs == A.shape[0]

# Exemple : Matrice à tester
A = np.array([
    [4, 1, 1],
    [1, 4, 1],
    [1, 1, 4]
])

# Vérification
if est_diagonalisable(A):
    print("La matrice est diagonalisable.")
else:
    print("La matrice n'est pas diagonalisable.")


La matrice est diagonalisable.


In [23]:
 est_diagonalisable(B)

True

In [11]:
#Polyhnome caracteristique
I=np.array([[1,0,0],[0,1,0],[0,0,1]])
k=np.random.randint(0,10)
B=np.dot(I,k)
B= -B
poly=A+B
poly


array([[-4, -1,  4],
       [ 3, -3, -1],
       [ 2,  1, -6]])

In [12]:
np.dot(poly,k)

array([[-20,  -5,  20],
       [ 15, -15,  -5],
       [ 10,   5, -30]])